[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CAC5040980>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/fc9995e5-8e5a-418d-811d-7560f503bfc8
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CAC5040290>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/fc9995e5-8e5a-418d-811d-7560f503bfc8
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CAC5040680>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/fc9995e5-8e5a-418d-811d-7560f503bfc8