[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023725A4ED20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ffd42f94-4120-4b2d-8943-03258075fa4b
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023725A4F1A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ffd42f94-4120-4b2d-8943-03258075fa4b
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023725A4ED50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ffd42f94-4120-4b2d-8943-03258075fa4b