[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024A556F6930>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/01f59509-9b6e-4d9b-b9ec-2413f580623d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024A556F5D90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/01f59509-9b6e-4d9b-b9ec-2413f580623d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024A556F6C30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/01f59509-9b6e-4d9b-b9ec-2413f580623d