[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F875941EB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c962349a-59e6-4ed4-87c5-f7d7e5b39083
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F875942510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c962349a-59e6-4ed4-87c5-f7d7e5b39083
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F875942780>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c962349a-59e6-4ed4-87c5-f7d7e5b39083