[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EC47515820>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/949c2096-cecd-4cfd-b52c-5cc6408e3f68/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EC475158E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/949c2096-cecd-4cfd-b52c-5cc6408e3f68/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EC47515AC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/949c2096-cecd-4cfd-b52c-5cc6408e3f68/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EC47515EE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/949c2096-cecd-4cfd-b52c-5cc6408e3f68
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EC475160F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/949c2096-cecd-4cfd-b52c-5cc6408e3f68
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EC475162D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/949c2096-cecd-4cfd-b52c-5cc6408e3f68