[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CAC50644A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1c9f494d-1d32-4656-9f6e-4a25135bfeb3
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CAC5064440>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1c9f494d-1d32-4656-9f6e-4a25135bfeb3
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CAC5064620>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1c9f494d-1d32-4656-9f6e-4a25135bfeb3