[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CAC50430E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/657d2246-53fd-42a4-938c-aec355889313
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CAC50407D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/657d2246-53fd-42a4-938c-aec355889313
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CAC5042D20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/657d2246-53fd-42a4-938c-aec355889313