[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B24AC1220>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7d5d5182-91a7-4618-8642-be56ceedbb20
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B24AC1580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7d5d5182-91a7-4618-8642-be56ceedbb20
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B24AC1280>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7d5d5182-91a7-4618-8642-be56ceedbb20