[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BD35F567E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/eebd70c2-48c0-436d-9983-d6683414d1fc
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BD35183A70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/eebd70c2-48c0-436d-9983-d6683414d1fc
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BD35F56750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/eebd70c2-48c0-436d-9983-d6683414d1fc